/* EduNexa V13 - Faculty + Student requested enhancements. Existing modules remain intact. */
(function(){
  const A=()=>window.EduNexaAPI;
  const escv=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const user=()=>window.currentUser||{};
  const notify=msg=>typeof toast==='function'&&toast(msg);
  const modal=(title,html)=>{ if(typeof openModal==='function'){openModal(title); const b=document.getElementById('modalBody'); if(b)b.innerHTML=html;} };

  async function loadAssess(type,history=false){ return A().request('/faculty/assessments/'+type+(history?'?history=true':'')); }
  async function assessmentDetail(type,id){ return A().request('/faculty/assessments/'+type+'/'+id); }

  function renderAssessmentList(type){
    const el=document.getElementById(type==='test'?'facultyTestList':'facultyAssignmentList'); if(!el)return;
    loadAssess(type,false).then(items=>{
      const label=type==='test'?'Test':'Assignment';
      el.innerHTML=(items||[]).map(x=>`<div class="item" style="margin-bottom:10px"><div class="item-top"><div><b>${escv(x.title)}</b><p>${escv(x.subject)} • ${escv(x.class_name||'')} • Due: ${escv(x.due_date||'')}</p></div><span class="badge blue">Seen ${x.seen_count||0} • Completed ${x.completed_count||0}</span></div><div class="actions"><button class="btn secondary" onclick="eduViewAssessment('${type}',${x.id})">View</button><button class="btn secondary" onclick="eduEditAssessment('${type}',${x.id})">Edit</button></div></div>`).join('')||'<div class="empty">No published '+label.toLowerCase()+'s.</div>';
      if(!el.parentElement.querySelector('.edu-history-btn')){
        const btn=document.createElement('button'); btn.className='btn secondary edu-history-btn'; btn.textContent='History — View All'; btn.onclick=()=>eduAssessmentHistory(type); el.parentElement.appendChild(btn);
      }
    }).catch(e=>console.warn('Assessment load',e));
  }
  window.eduViewAssessment=async function(type,id){
    try{const x=await assessmentDetail(type,id); const q=x.questions_json?JSON.parse(x.questions_json||'[]'):[];
      modal((type==='test'?'Test':'Assignment')+' Full Details',`<div class="grid2"><div class="item"><b>Title</b><p>${escv(x.title)}</p></div><div class="item"><b>Subject</b><p>${escv(x.subject)}</p></div><div class="item"><b>Target Class</b><p>${escv(x.class_name)}</p></div><div class="item"><b>Due Date</b><p>${escv(x.due_date)}</p></div><div class="item"><b>Students Seen</b><p>${x.seen_count||0}</p></div><div class="item"><b>Students Completed</b><p>${x.completed_count||0}</p></div></div><div class="card"><h3>Full Description</h3><p>${escv(x.description||'No description')}</p>${type==='test'?'<h3>Questions</h3><ol>'+q.map(a=>'<li>'+escv(a.q||a.question||a.text||'Question')+'</li>').join('')+'</ol>':''}</div><div class="table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Status</th><th>Mark</th><th>Submitted</th></tr></thead><tbody>${(x.submissions||[]).map(s=>`<tr><td>${escv(s.student_name)}</td><td>${escv(s.student_code)}</td><td>${escv(s.status)}</td><td>${escv(s.mark??'-')}</td><td>${escv(s.submitted_at||'-')}</td></tr>`).join('')||'<tr><td colspan="5">No completed submissions yet.</td></tr>'}</tbody></table></div>`);
    }catch(e){notify('Unable to load assessment details.');}
  };
  window.eduEditAssessment=async function(type,id){
    try{const x=await assessmentDetail(type,id); modal('Edit '+(type==='test'?'Test':'Assignment'),`<form onsubmit="eduSaveAssessment(event,'${type}',${id})"><div class="form-grid"><div class="form-group"><label>Title</label><input id="eaTitle" class="control" value="${escv(x.title)}" required></div><div class="form-group"><label>Subject</label><input id="eaSubject" class="control" value="${escv(x.subject)}" required></div><div class="form-group"><label>Target Class</label><input id="eaClass" class="control" value="${escv(x.class_name)}" required></div><div class="form-group"><label>Due Date</label><input id="eaDue" type="date" class="control" value="${escv((x.due_date||'').slice(0,10))}" required></div><div class="form-group full"><label>Description</label><textarea id="eaDesc" class="control" rows="4">${escv(x.description||'')}</textarea></div></div><button class="btn primary">Save Changes</button></form>`);}catch(e){notify('Unable to edit assessment.');}
  };
  window.eduSaveAssessment=async function(ev,type,id){ev.preventDefault(); try{await A().request('/faculty/assessments/'+type+'/'+id,{method:'PUT',body:JSON.stringify({title:document.getElementById('eaTitle').value,subject:document.getElementById('eaSubject').value,class_name:document.getElementById('eaClass').value,due_date:document.getElementById('eaDue').value,description:document.getElementById('eaDesc').value})}); closeModal&&closeModal(); renderAssessmentList(type); notify('Updated successfully.');}catch(e){notify('Update failed.');}};
  window.eduAssessmentHistory=async function(type){try{const all=await loadAssess(type,true); modal((type==='test'?'Test':'Assignment')+' History',`<p>All published ${type}s are stored in SQLite. The main module shows only the latest 3.</p><div class="table-wrap"><table><thead><tr><th>Title</th><th>Class</th><th>Due</th><th>Seen</th><th>Completed</th><th>View</th></tr></thead><tbody>${all.map(x=>`<tr><td>${escv(x.title)}</td><td>${escv(x.class_name)}</td><td>${escv(x.due_date)}</td><td>${x.seen_count||0}</td><td>${x.completed_count||0}</td><td><button class="btn secondary" onclick="eduViewAssessment('${type}',${x.id})">View</button></td></tr>`).join('')||'<tr><td colspan="6">No history.</td></tr>'}</tbody></table></div>`);}catch(e){notify('History unavailable.');}};

  window.createTest=async function(ev){ev.preventDefault(); try{const q=[1,2].map(n=>{const p=document.getElementById('q'+n).value.split('|').map(x=>x.trim()); if(p.length<6)throw Error('Question '+n+' format is invalid.'); return {q:p[0],opts:p.slice(1,5),ans:Number(p[5])-1};}); const p={title:document.getElementById('testTitle').value.trim(),subject:document.getElementById('testSubject').value.trim(),class_name:document.getElementById('testClass')?.value||user().className||user().classesHandled?.[0]||'II B.Sc Data Analytics',due_date:document.getElementById('testDue').value,description:'Faculty published test',questions:q,max_mark:100}; const r=await A().request('/faculty/assessments/test',{method:'POST',body:JSON.stringify(p)}); ev.target.reset(); if(typeof refreshAll==='function')refreshAll(); renderAssessmentList('test'); notify('Test published. '+(r.notified_students||0)+' targeted students notified.');}catch(e){notify(e.message||'Test publish failed.');}};
  window.createAssignment=async function(ev){ev.preventDefault(); try{const p={title:document.getElementById('asTitle').value.trim(),subject:document.getElementById('asSubject').value.trim(),class_name:document.getElementById('asClass').value, due_date:document.getElementById('asDue').value,description:document.getElementById('asDesc').value.trim(),max_mark:100}; const r=await A().request('/faculty/assessments/assignment',{method:'POST',body:JSON.stringify(p)}); ev.target.reset(); if(typeof refreshAll==='function')refreshAll(); renderAssessmentList('assignment'); notify('Assignment published. '+(r.notified_students||0)+' targeted students notified.');}catch(e){notify(e.message||'Assignment publish failed.');}};

  async function renderAttendance(){const page=document.getElementById('faculty-attendance');if(!page)return; const card=page.querySelector('.card'); if(!card)return; try{const d=await A().request('/faculty/attendance/overview'); card.innerHTML=(d.classes||[]).map(c=>`<div class="card"><div class="card-head"><div><h3>${escv(c.name)}</h3><p>${escv(c.department)} • ${escv(c.batch||'')} • Semester ${escv(c.semester||'')} • Section ${escv(c.section||'')}</p></div></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Present</th><th>Total Days</th><th>Attendance %</th><th>Action</th></tr></thead><tbody>${(c.students||[]).map(s=>`<tr><td>${escv(s.name)}</td><td>${escv(s.student_id)}</td><td>${s.present_days}</td><td>${s.total_days}</td><td><b>${s.attendance_percentage}%</b></td><td><button class="btn secondary" onclick="eduViewAttendanceStudent(${s.id})">View</button></td></tr>`).join('')||'<tr><td colspan="6">No students.</td></tr>'}</tbody></table></div></div>`).join('')||'<div class="empty">No handled classes found.</div>';}catch(e){console.warn(e);}}
  window.eduViewAttendanceStudent=async function(id){try{const s=await A().request('/faculty/attendance/student/'+id); modal('Attendance — '+escv(s.name),`<div class="item"><b>Attendance Percentage</b><p>${s.attendance_percentage}%</p></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Subject</th><th>Status</th><th>Faculty</th></tr></thead><tbody>${(s.records||[]).map(r=>`<tr><td>${escv(r.date)}</td><td>${escv(r.subject)}</td><td>${escv(r.status)}</td><td>${escv(r.faculty_name||'-')}</td></tr>`).join('')||'<tr><td colspan="4">No attendance records.</td></tr>'}</tbody></table></div>`);}catch(e){notify('Attendance details unavailable.');}};

  window.renderFacultyLeaves=async function(){const el=document.getElementById('facultyLeaves');if(!el)return; try{const rows=await A().request('/faculty/leaves/all'); const pending=(rows||[]).filter(x=>String(x.status).toLowerCase()==='pending'); el.innerHTML=`<div class="card"><div class="card-head"><div><h3>Pending Leave Requests</h3><p>Accepted/declined requests are hidden here but remain stored in SQLite.</p></div><button class="btn secondary" onclick="eduAllLeaves()">All Requests</button></div></div>`+(pending.map(l=>`<div class="card"><div class="item-top"><div><h3>${escv(l.student_name)}</h3><p>${escv(l.leave_type)} • ${escv(l.from_date)} → ${escv(l.to_date)} • ${escv(l.reason)}</p></div><span class="badge yellow">Pending</span></div><div class="actions"><button class="btn success" onclick="eduReviewLeave(${l.id},'approved')">Accept</button><button class="btn danger" onclick="eduReviewLeave(${l.id},'declined')">Decline</button></div></div>`).join('')||'<div class="card empty">No pending leave requests.</div>');}catch(e){notify('Leave requests unavailable.');}};
  window.eduReviewLeave=async function(id,status){try{await A().request('/leaves/'+id,{method:'PUT',body:JSON.stringify({status:status,review_note:''})}); if(typeof renderFacultyLeaves==='function')renderFacultyLeaves(); notify(status==='approved'?'Accepted. Student notification sent.':'Declined. Student notification sent.');}catch(e){notify('Leave review failed.');}};
  window.eduAllLeaves=async function(){const form=`<div class="form-grid"><div class="form-group"><label>Student Name</label><input id="lfStudent" class="control" placeholder="Name"></div><div class="form-group"><label>Status</label><select id="lfStatus" class="control"><option value="">All</option><option value="pending">Pending</option><option value="approved">Accepted</option><option value="declined">Declined</option></select></div><div class="form-group"><label>Month</label><input id="lfMonth" type="month" class="control"></div><div class="form-group"><label>Date</label><input id="lfDate" type="date" class="control"></div></div><button class="btn primary" onclick="eduFilterLeaves()">Apply Filter</button><div id="eduLeaveResults" style="margin-top:15px"></div>`; modal('All Leave Requests',form); eduFilterLeaves();};
  window.eduFilterLeaves=async function(){try{const q=new URLSearchParams(); const n=document.getElementById('lfStudent')?.value;const st=document.getElementById('lfStatus')?.value;const m=document.getElementById('lfMonth')?.value;const d=document.getElementById('lfDate')?.value;if(n)q.set('student_name',n);if(st)q.set('status',st);if(m)q.set('month',m);if(d)q.set('date',d);const rows=await A().request('/faculty/leaves/all?'+q.toString());const el=document.getElementById('eduLeaveResults'); if(el)el.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Date</th><th>Type</th><th>Reason</th><th>Status</th><th>Reviewed</th></tr></thead><tbody>${rows.map(l=>`<tr><td>${escv(l.student_name)}<br><small>${escv(l.student_code||'')}</small></td><td>${escv(l.from_date)} → ${escv(l.to_date)}</td><td>${escv(l.leave_type)}</td><td>${escv(l.reason)}</td><td>${escv(l.status)}</td><td>${escv(l.reviewed_at||'-')}</td></tr>`).join('')||'<tr><td colspan="6">No matching requests.</td></tr>'}</tbody></table></div>`;}catch(e){notify('Filter failed.');}};

  async function studentClass(){const page=document.getElementById('student-timetable');if(!page)return;try{const d=await A().request('/student/class-details'); let info=page.querySelector('#eduClassInfo');if(!info){info=document.createElement('div');info.id='eduClassInfo';page.insertBefore(info,page.querySelector('.card'));} info.innerHTML=`<div class="card"><h3>🏫 Class Details</h3><div class="grid3"><div class="item"><b>Class & Section</b><p>${escv(d.class_name)} • ${escv(d.section||'')}</p></div><div class="item"><b>Year / Batch</b><p>${escv(d.batch)}</p></div><div class="item"><b>Department</b><p>${escv(d.department_name)}</p></div><div class="item"><b>Class Adviser</b><p>${escv(d.class_adviser_name||'-')}</p></div><div class="item"><b>Mentor</b><p>${escv(d.mentor_name||'-')}</p></div><div class="item"><b>HOD</b><p>${escv(d.hod_name||'-')}</p></div></div></div>`; const table=page.querySelector('#studentTimetable');if(table)table.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Day</th><th>Period</th><th>Time</th><th>Subject</th><th>Subject Faculty</th><th>Room</th></tr></thead><tbody>${(d.subject_faculty||[]).map(r=>`<tr><td>${escv(r.day)}</td><td>${escv(r.period)}</td><td>${escv(r.start_time)} - ${escv(r.end_time)}</td><td>${escv(r.subject)}</td><td>${escv(r.faculty_name)}</td><td>${escv(r.room||'-')}</td></tr>`).join('')||'<tr><td colspan="6">No timetable entries.</td></tr>'}</tbody></table></div>`;}catch(e){console.warn('Class details',e);}}

  function boot(){setTimeout(()=>{renderAssessmentList('test');renderAssessmentList('assignment');renderAttendance();studentClass();},500);}
  const oldRefresh=window.refreshAll; window.refreshAll=function(){if(oldRefresh)oldRefresh();setTimeout(()=>{renderAssessmentList('test');renderAssessmentList('assignment');if(user().role==='faculty')renderAttendance();if(user().role==='student')studentClass();},250);};
  document.addEventListener('DOMContentLoaded',boot);
})();
